apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-2
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
